# Generated by Django 6.0.6 on 2026-07-11 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('contact_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('whatsapp_number', models.CharField(help_text='Include country code, e.g., +234...', max_length=20)),
                ('consultation_type', models.CharField(choices=[('AI Strategy', 'AI Strategy Consultation'), ('Robotics', 'Robotics Consultation'), ('Product Demo', 'Product Demo'), ('Technical Discovery', 'Technical Discovery Session'), ('Investor Meeting', 'Investor Meeting'), ('Research Collaboration', 'Research Collaboration')], max_length=50)),
                ('available_start_date', models.DateField(verbose_name='Available From Date')),
                ('available_end_date', models.DateField(verbose_name='Available Until Date')),
                ('available_start_time', models.TimeField(verbose_name='Available From Time')),
                ('available_end_time', models.TimeField(verbose_name='Available Until Time')),
                ('project_description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Pending', max_length=20)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
