# Generated by Django 6.0.6 on 2026-07-26 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('inquiry_type', models.CharField(choices=[('Collaborate on a project', 'Collaborate on a project'), ('Invest in my software', 'Invest in my software'), ('Buy a software license', 'Buy a software license'), ('Ask for technical help', 'Ask for technical help'), ('Hire me for contract work', 'Hire me for contract work')], max_length=100)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Pending', max_length=20)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
